### 1. Imports

In [1]:
import pandas as pd
import numpy as np

### 2. Reading data

In [2]:
df = pd.read_csv("../data/players_raw.csv")

In [3]:
df.head()

,Category,level_1,Rank,Player,Passes,Passes Completed,Passing Accuracy (%),Crosses,Crossing Accuracy (%),Take-Ons Completed,...,Offers Inside Team Shape,Offers Outside Team Shape,Receptions In Behind,Receptions Between Midfield And Defensive Line,Receptions Under Pressure,Player Involvements,Top Speed (km/h),High Speed Running,Sprints,Total Distance (m)
0,General,0,1,Rodri,799.0,747.0,93.0,3.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,General,1,2,Pau Cubarsi,690.0,668.0,97.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,General,2,3,Aymeric Laporte,660.0,618.0,94.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,General,3,4,Leandro Paredes,565.0,532.0,94.0,2.0,50.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,General,4,5,Marc Guehi,532.0,514.0,97.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(400, 51)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 51 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Category                                        400 non-null    str
 1   level_1                                         400 non-null    int64
 2   Rank                                            400 non-null    int64
 3   Player                                          400 non-null    str
 4   Passes                                          100 non-null    float64
 5   Passes Completed                                100 non-null    float64
 6   Passing Accuracy (%)                            100 non-null    float64
 7   Crosses                                         100 non-null    float64
 8   Crossing Accuracy (%)                           100 non-null    float64
 9   Take-Ons Completed                              100 non-null    float64
 10  Defensive Linebreaks Attempted                  100 non-null    float64
 11  Defensive Linebreaks Acc (%)                    100 non-null    float64
 12  Switches of Play Attempted                      100 non-null    float64
 13  Switches of Play Acc (%)                        100 non-null    float64
 14  Assists                                         50 non-null     float64
 15  Attempts On Target                              50 non-null     float64
 16  Attempts At Goal                                50 non-null     float64
 17  Attempts At Goal Conv. Rate (%)                 50 non-null     float64
 18  Attempts Inside the Penalty Area                50 non-null     float64
 19  Attempts Outside the Penalty Area               50 non-null     float64
 20  Headed Attempts at Goal                         50 non-null     float64
 21  xG                                              50 non-null     float64
 22  xG Efficiency                                   50 non-null     str
 23  Corners                                         50 non-null     float64
 24  Own Goals                                       50 non-null     float64
 25  Forced Turnovers                                50 non-null     float64
 26  Defensive Pressures Applied                     50 non-null     float64
 27  Defensive Pressures Directly Applied            50 non-null     float64
 28  Fouls Against                                   50 non-null     float64
 29  Fouls For                                       50 non-null     float64
 30  Yellow Cards                                    50 non-null     float64
 31  Red Cards                                       50 non-null     float64
 32  Indirect Red Cards                              50 non-null     float64
 33  Offsides                                        50 non-null     float64
 34  Goalkeeper Saves                                50 non-null     float64
 35  Goalkeeper Actions Inside the Penalty Area      50 non-null     float64
 36  Goalkeeper Actions Outside the Penalty Area     50 non-null     float64
 37  Offers To Receive                               50 non-null     float64
 38  Offers In Behind                                50 non-null     float64
 39  Offers In Between                               50 non-null     float64
 40  Offers In Front                                 50 non-null     float64
 41  Offers Inside Team Shape                        50 non-null     float64
 42  Offers Outside Team Shape                       50 non-null     float64
 43  Receptions In Behind                            50 non-null     float64
 44  Receptions Between Midfield And Defensive Line  50 non-null     float64
 45  Receptions Under Pressure                       50 non-null     float64
 46  Player Involvements                             50 non-null     float64
 47  Top Speed (km/h)                                50 non-null     float64
 48  High Speed Running                              50 non-null     float64
 49  Sprints                                         50 non-null     float64
 50  Total Distance (m)                              50 non-null     float64
dtypes: float64(46), int64(2), str(3)
memory usage: 168.6 KB

### 3. Cheaking null values

In [6]:
df.isnull().sum()

Category                                            0
level_1                                             0
Rank                                                0
Player                                              0
Passes                                            300
Passes Completed                                  300
Passing Accuracy (%)                              300
Crosses                                           300
Crossing Accuracy (%)                             300
Take-Ons Completed                                300
Defensive Linebreaks Attempted                    300
Defensive Linebreaks Acc (%)                      300
Switches of Play Attempted                        300
Switches of Play Acc (%)                          300
Assists                                           350
Attempts On Target                                350
Attempts At Goal                                  350
Attempts At Goal Conv. Rate (%)                   350
Attempts Inside the Penalty Area                  350
Attempts Outside the Penalty Area                 350
Headed Attempts at Goal                           350
xG                                                350
xG Efficiency                                     350
Corners                                           350
Own Goals                                         350
Forced Turnovers                                  350
Defensive Pressures Applied                       350
Defensive Pressures Directly Applied              350
Fouls Against                                     350
Fouls For                                         350
Yellow Cards                                      350
Red Cards                                         350
Indirect Red Cards                                350
Offsides                                          350
Goalkeeper Saves                                  350
Goalkeeper Actions Inside the Penalty Area        350
Goalkeeper Actions Outside the Penalty Area       350
Offers To Receive                                 350
Offers In Behind                                  350
Offers In Between                                 350
Offers In Front                                   350
Offers Inside Team Shape                          350
Offers Outside Team Shape                         350
Receptions In Behind                              350
Receptions Between Midfield And Defensive Line    350
Receptions Under Pressure                         350
Player Involvements                               350
Top Speed (km/h)                                  350
High Speed Running                                350
Sprints                                           350
Total Distance (m)                                350
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

### 4. Strip extra spaces

In [8]:
df["Player"] = df["Player"].str.strip()
df["Category"] = df["Category"].str.strip()

### 5. Clean xG Efficiency

In [9]:
df["xG Efficiency"] = (
    df["xG Efficiency"]
    .str.replace("x", "", regex=False)
)

### 6. Fill missing values

In [10]:
numeric_cols = df.select_dtypes(include=["number"]).columns

df[numeric_cols] = df[numeric_cols].fillna(0)
df["xG Efficiency"] = df["xG Efficiency"].fillna("0")

### 7. Convert xG Efficiency to numeric

In [11]:
df["xG Efficiency"] = pd.to_numeric(df["xG Efficiency"], errors="coerce").fillna(0)

In [12]:
df.isnull().sum()

Category                                          0
level_1                                           0
Rank                                              0
Player                                            0
Passes                                            0
Passes Completed                                  0
Passing Accuracy (%)                              0
Crosses                                           0
Crossing Accuracy (%)                             0
Take-Ons Completed                                0
Defensive Linebreaks Attempted                    0
Defensive Linebreaks Acc (%)                      0
Switches of Play Attempted                        0
Switches of Play Acc (%)                          0
Assists                                           0
Attempts On Target                                0
Attempts At Goal                                  0
Attempts At Goal Conv. Rate (%)                   0
Attempts Inside the Penalty Area                  0
Attempts Outside the Penalty Area                 0
Headed Attempts at Goal                           0
xG                                                0
xG Efficiency                                     0
Corners                                           0
Own Goals                                         0
Forced Turnovers                                  0
Defensive Pressures Applied                       0
Defensive Pressures Directly Applied              0
Fouls Against                                     0
Fouls For                                         0
Yellow Cards                                      0
Red Cards                                         0
Indirect Red Cards                                0
Offsides                                          0
Goalkeeper Saves                                  0
Goalkeeper Actions Inside the Penalty Area        0
Goalkeeper Actions Outside the Penalty Area       0
Offers To Receive                                 0
Offers In Behind                                  0
Offers In Between                                 0
Offers In Front                                   0
Offers Inside Team Shape                          0
Offers Outside Team Shape                         0
Receptions In Behind                              0
Receptions Between Midfield And Defensive Line    0
Receptions Under Pressure                         0
Player Involvements                               0
Top Speed (km/h)                                  0
High Speed Running                                0
Sprints                                           0
Total Distance (m)                                0
dtype: int64

### 8. Creating Goal Contribution

In [13]:
df["Goal Contribution"] = df["Assists"] + df["Attempts At Goal"]

### 9. Creating Goal Efficiency

In [14]:
df["Goal Efficiency"] = np.where(
    df["Attempts At Goal"] > 0,
    df["Assists"] / df["Attempts At Goal"],
    0
)

### 10.Checking the new columns

In [15]:
df[["Player", "Assists", "Attempts At Goal", "Goal Contribution", "Goal Efficiency"]].head()

,Player,Assists,Attempts At Goal,Goal Contribution,Goal Efficiency
0,Rodri,0.0,0.0,0.0,0.0
1,Pau Cubarsi,0.0,0.0,0.0,0.0
2,Aymeric Laporte,0.0,0.0,0.0,0.0
3,Leandro Paredes,0.0,0.0,0.0,0.0
4,Marc Guehi,0.0,0.0,0.0,0.0

### 11. Save the cleaned dataset

In [16]:
df.to_csv("../data/players_cleaned.csv", index=False)